peterka_shard = class({})
function peterka_shard:IsStealable() return false end
function peterka_shard:OnSpellStart()
    EmitGlobalSound("Item.PickUpGemWorld")
	local newItem = CreateItem( "item_bag_of_gold_2", nil, nil )
    local newItem2 = CreateItem( "item_bag_of_gold_2", nil, nil )
    local newItem3 = CreateItem( "item_bag_of_gold_2", nil, nil )
    local newItem4 = CreateItem( "item_bag_of_gold_2", nil, nil )
	local drop = CreateItemOnPositionForLaunch( self:GetAbsOrigin(), newItem )
    local drop2 = CreateItemOnPositionForLaunch( self:GetAbsOrigin(), newItem2 )
    local drop3 = CreateItemOnPositionForLaunch( self:GetAbsOrigin(), newItem3 )
    local drop4 = CreateItemOnPositionForLaunch( self:GetAbsOrigin(), newItem4 )
	local dropRadius = RandomFloat( 400, 500 )
    local dropRadius2 = RandomFloat( -400, 500 )
	newItem:LaunchLootInitialHeight( false, 0, 500, 0.75, self:GetAbsOrigin() + RandomVector( dropRadius ) )
    newItem2:LaunchLootInitialHeight( false, 0, 500, 0.75, self:GetAbsOrigin() - RandomVector( dropRadius ) )
    newItem3:LaunchLootInitialHeight( false, 0, 500, 0.75, self:GetAbsOrigin() + RandomVector( dropRadius2 ) )
    newItem4:LaunchLootInitialHeight( false, 0, 500, 0.75, self:GetAbsOrigin() - RandomVector( dropRadius2 ) )
	newItem:SetContextThink( "KillLoot", function() return COverthrowGameMode:KillLoot( newItem, drop ) end, 20 )
    newItem2:SetContextThink( "KillLoot", function() return COverthrowGameMode:KillLoot( newItem2, drop2 ) end, 20 )
    newItem3:SetContextThink( "KillLoot", function() return COverthrowGameMode:KillLoot( newItem3, drop3 ) end, 20 )
    newItem4:SetContextThink( "KillLoot", function() return COverthrowGameMode:KillLoot( newItem4, drop4 ) end, 20 )
end